--This is the decoded GKTV's PB2 Cheat
--Any comment i put is generated by me, not from original script (cuz they dont have 1)
--Usual fancy nonsense to do
gg.toast(os.date("Date: %A %d/%m/%Y ⏰%X [%p]"))
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_C_BSS | gg.REGION_ANONYMOUS | gg.REGION_CODE_APP)

prompt = gg.prompt({"Password"},{},{[1]="num"})
if prompt[1] == "183628" then
	gg.alert("Correct Password✔")
else
	gg.alert("⚠️Invalid Password⚠️")
	os.exit()
end




function HOME()
--show cheat options
	local menu = gg.choice({
		"⭕Traffic Chaos: ON",
		"⭕Traffic Chaos: OFF",
		"⭕Funny Run: ON",
		"⭕Funny Run: OFF",
		"⭕Fly: ON",
		"⭕Fly: OFF",
		"⭕Sun: ON",
		"⭕Sun: OFF",
		"⭕Colored trees: ON",
		"⭕Colored trees: OFF",
		"⭕Big Flamethrower: ON",
		"⭕Big Flamethrower: OFF",
		"⭕Wall Hack: ON",
		"⭕Wall Hack: OFF",
		"⭕Enable Shadows",
		"⭕Disable Shadows",
		"⭕Colored People's (ESP): ON",
		"⭕Colored People's (ESP): OFF",
		"⭕Weapon Ammo Hack",
		"⭕Speed Hack",
		"⭕Change Nickname",
		"⭕Delete All Names",
		"⭕Invisible Nickname",
		"⭕Copy YouTube",
		"🔙Exit"
	}, nil, "PB2 Cheat by GKTV: Decompiled")
--show fancy flex nonsense because why not
	gg.toast("Script By GKTV (Pumpkin Hacker)")
	if menu == 1 then h2() end   -- Traffic Chaos ON - ALREADY_ADDED, FAIL
	if menu == 2 then h3() end   -- Traffic Chaos OFF
	if menu == 3 then h14() end  -- Funny Run ON - ADDED
	if menu == 4 then h15() end  -- Funny Run OFF
	if menu == 5 then h4() end   -- Fly ON - ALREADY_ADDED, WORKS
	if menu == 6 then h5() end   -- Fly OFF
	if menu == 7 then h10() end  -- Sun ON - FAIL
	if menu == 8 then h11() end  -- Sun OFF
	if menu == 9 then h12() end  -- Colored trees ON - VERIFIED_WORKS NO_NOTES_REASON:forgetlol
	if menu == 10 then h13() end -- Colored trees OFF
	if menu == 11 then h16() end -- Big Flamethrower ON - FAIL
	if menu == 12 then h17() end -- Big Flamethrower OFF
	if menu == 13 then h18() end -- Wall Hack ON - ALTERNATIVE_ADDED
	if menu == 14 then h19() end -- Wall Hack OFF
	if menu == 15 then h21() end -- Enable Shadows
	if menu == 16 then h20() end -- Disable Shadows - VERIFIED_WORKS, TYPE=CODE_APP RECOMMENDED_HACK_VALUE=ENABLE:0;DISABLE:-1,0
	if menu == 17 then h22() end -- Colored People's (ESP) ON - KINDA_WORKS[REASON]=idk wut this does TYPE=CODE_APP >0&99999999 will disable shadow on peoples
	if menu == 18 then h23() end -- Colored People's (ESP) OFF
	if menu == 19 then h1() end  -- Weapon Ammo Hack - IDK
	if menu == 20 then h8() end  -- Speed Hack - IDK
	if menu == 21 then h6() end  -- Change Nickname - PREDICTION_FAIL_90
	if menu == 22 then h7() end  -- Delete All Names - PREDICTION_FAIL_90
	if menu == 23 then h9() end  -- Invisible Nickname - PREDICTION_FAIL_90
	if menu == 24 then gg.copyText("https://youtube.com/channel/UCjTmua2y1_R4uriGRMrjigg") end
	if menu == 25 then EXIT() end-- Exit
--this is generated by me
	HOMEDM = -1
end

function h1() -- Weapon Ammo Hack 
--Variables are generated by me, not from original
	CH = gg.prompt({'Ammo'},{},{[1]='num'})
	gg.searchNumber(CH[1],gg.TYPE_WORD,gg.SIGN_EQUAL,0,-1)
--This is prediction (95% accurate):
	gg.toast(15)
	gg.sleep(999)
	gg.toast(14)
	gg.sleep(999)
	gg.toast(13)
	gg.sleep(999)
	gg.toast(12)
	gg.sleep(999)
	gg.toast(11)
	gg.sleep(999)
	gg.toast(10)
	gg.sleep(999)
	gg.toast(9)
	gg.sleep(999)
	gg.toast(8)
	gg.sleep(999)
	gg.toast(7)
	gg.sleep(999)
	gg.toast(6)
	gg.sleep(999)
	gg.toast(5)
	gg.sleep(999)
	gg.toast(4)
	gg.sleep(999)
	gg.toast(3)
	gg.sleep(999)
	gg.toast(2)
	gg.sleep(999)
	gg.toast(1)
--idk this 1 so i generated it myself lol
	CH = gg.prompt({'Change Ammo:','Freeze'},{},{[1]='num',[2]='checkbox'})
	gg.refineNumber(CH[1])
--bruh idk this 1
--f2()
--f1()
--This is prediction (55% accurate)
	gg.clearResults()
	gg.toast("Hacked!")
end

function h2() -- Traffic Chaos ON 
	gg.searchNumber("0.89868283272F;0.91149836779F;0.92426908016F;0.93699574471F;0.9496794343F;0.9623208046F;0.97492086887F;0.98748034239F;1.0F;1.01248061657F;1.02492284775F;1.03732740879F;1.04969501495F;1.06202638149F;1.07432198524F;1.08658242226F;1.09880852699F;1.11100065708F;1.12315940857F;1.1352853775F;1.14737904072F;1.15944087505F;1.17147147655F;1.18347120285F;1.19544064999F;1.20738017559F;1.2192902565F;1.23117136955F::109", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	gg.refineNumber("1.0")
	gg.getResults(50)
	gg.editAll("-500")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h3() -- Traffic Chaos OFF 
	gg.searchNumber("0.89868283272F;-500.0F;1.14737904072F;1.15944087505F;1.17147147655F;1.18347120285F;1.19544064999F;1.20738017559F;1.2192902565F;1.23117136955F::109", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	gg.refineNumber("-500")
	gg.getResults(50)
	gg.editAll("1.0")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h4() -- Fly ON 
	gg.searchNumber("0.25F;1067869798D;1067869798D;1065353216D;1080326881D;1065353216D::37", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(5000)
	gg.editAll("-20")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h5() -- Fly OFF 
	gg.searchNumber("-20.0F;1067869798D;1067869798D;1065353216D;1080326881D;1065353216D::37", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(5000)
	gg.editAll("0.25")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h6() -- Change Nickname 
--Variables are generated by me, not from original
	CH = gg.prompt({'Nickname','Change nickname'},{[1]='Player',[2]='Player2'},{[1]='text',[2]='text'})
	gg.searchNumber(":"..CH[1], gg.TYPE_BYTE, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(5555)
	gg.editAll(CH[2])
	gg.clearResults()
	gg.toast("Hacked!")
end

function h7() -- Delete all names 
--idk bout dis 1 bruuh
	gg.searchNumber(":Toasted", gg.TYPE_BYTE, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(5555)
	gg.editAll("::Wasted:Nuked:Drowned:OBLITERATED:Your team won:You scored:You finished:Your team scored:DEFEND:STEAL:BASE:SPLATTERED:DELIVER:DOMINATE:CAPTURE:KILL")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h8() -- Speed Hack 
--Variables are generated by me, not from original
	CH = gg.prompt({'Speed: [1; 8]'},{[1]='1'},{[1]='number'})
	gg.setSpeed(CH[1])
	gg.clearResults()
	gg.toast("Hacked!")
end

function h9() -- Invisible Nickname 
--Variables are generated by me, not from original
	CH = gg.prompt({'Nickname'},{[1]='Player'},{[1]='text'})
	gg.searchNumber(":"..CH[1], gg.TYPE_BYTE, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(5555)
	gg.editAll("")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h10() -- Sun ON 
	gg.searchNumber("1.5", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("999999999")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h11() -- Sun OFF 
	gg.searchNumber("999999999", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("1.5")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h12() -- Colored Trees ON 
	gg.searchNumber("0.04", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("-999999999")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h13() -- Colored Trees OFF 
	gg.searchNumber("-999999999", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("0.04")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h14() -- Funny Run ON 
--Values here are slightly changed to prevent coliding with other values when searching
	gg.searchNumber("0.004", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("-999999998")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h15() -- Funny Run OFF 
--Values here are slightly changed to prevent coliding with other values when searching
	gg.searchNumber("-999999998", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("0.04")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h16() -- Big Flamethrower ON 
	gg.searchNumber("0.9", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("5.999")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h17() -- Big Flamethrower OFF 
	gg.searchNumber("5.999", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("0.9")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h18() -- Wall Hack ON 
	gg.searchNumber("0.001", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("-1.00001")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h19() -- Wall Hack OFF 
	gg.searchNumber("-1.00001", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("0.001")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h20() -- Disable Shadow
	gg.searchNumber("0.0001", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("-999.999")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h21() -- Enable Shadow
	gg.searchNumber("-999.999", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("0.0001")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h22() -- Colored People's (ESP) ON
	gg.searchNumber("0.08", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("999.999")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h23() -- Colored People's (ESP) OFF
	gg.searchNumber("999.999", gg.TYPE_FLOAT, gg.SIGN_EQUAL, 0, -1)
	revert = gg.getResults(10000)
	gg.editAll("0.08")
	gg.clearResults()
	gg.toast("Hacked!")
end

function h24() -- ?? 
end

function EXIT()
	os.exit()
end

while true do
	if gg.isVisible() then
		gg.setVisible(false)
		HOMEDM = 1
	end
	if HOMEDM == 1 then
		HOME()
	end
end
