blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/ABJ4403/Payback2_CHEATus/discussions/2
    about: If you have feature to request, go to discussion instead

